name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches: [ main ]
  
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint --if-present
        
      - name: Type Check
        run: npm run typecheck --if-present
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create .nojekyll File
        run: touch dist/.nojekyll

      - name: Copy 404.html for SPA Routing
        run: cp public/404.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          clean-exclude: |
            .gitignore
            .nojekyll
          commit-message: "Deploy: ${{ github.event.head_commit.message || 'Manual deployment' }}"